name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc -exo pipefail {0}

    steps:
      - uses: actions/checkout@v1
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201008
      - uses: icepuma/rust-action@master
        with:
          args: which docker && cd tests && cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test